baseURL = 'https://www.zhulivictor.com/'
languageCode = 'en-us'
title = 'Li Zhu, Ph.D.'
theme = 'elegant'

[params]
  author = "Li Zhu"
  description = "Staff Research Engineer II at Samsung Research America"
  profileImage = "/images/profile.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
